//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Detail
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int st_id { get; set; }
        public string st_name { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
    }
}
